### PR TITLE
Head Rotation + Weather Packets + Gamemode Update

### PR DESCRIPTION
**Pull request by 7kasper**
Fixed the yaw clipping/jumping of pc clients' heads by applying a
constant.

### CODE REVIEW

**Comment by Shevchik** [comment]
So the pe yaw 256 degrees based?

**Comment by 7kasper** [comment]
It seems like in the pc packet it's 256 degrees while pocket expects 360 degree based. When I look at the yaw in F3 on the pc it is also based on 360 degrees, but while debugging the packet it never reached 180 degrees.

**Comment by NycuRO** [comment]
You can fix FOV?

**Comment by NycuRO** [comment]
<3

**Comment by 7kasper** [comment]
@NycuRO Is there anything wrong with the FOV? It only bugs while running, but I believe @DaMatrix fixed that.

**Comment by NycuRO** [comment]
@7kasper FOV isn't able to change..

**Comment by NycuRO** [comment]
@7kasper And chests isn't usable... Enchantments... and other. Can you fix that? Or metadata?

**Comment by 7kasper** [comment]
@NycuRO I enjoy your enthusiasm :) 

I have already implemented three things today and have to learn for an upcomming tests, but I'm sure we'll implement those features in some time. You'll have to wait though.

**Comment by NycuRO** [comment]
I need for SkyWars that :> @7kasper

**Comment by gdude2002** [comment]
@NycuRO Those requests are kinda out of scope of this pull request. Please give the developer some time.

@7kasper Apologies, they've been doing this on the Discord as well.

**Comment by MrPowerGamerBR** [comment]
@7kasper Shevchik said he won't implement inventories until Mojang adds server sided inventories to MCPE, because the current MCPE inventory system sucks.

**Comment by 7kasper** [comment]
@gdude2002 you're right. There's alot left to do. You know what the funny thing is though, protocol support seems more stable already than most pocket serversoftwares I tried :P

**Comment by gdude2002** [comment]
To expand on the inventory stuff, it's pretty much entirely client-side. Unfortunately, that means some of the packets you would need for a conventional implementation just don't exist - most of the time, you don't even know what GUI is open.

Mojang has stated that they are working on a client-side inventory, though.

**Comment by Shevchik** [comment]
Weather and gamemode change looks fine, still unsure about head rotation, this needs more investigation. Can you split those pull requests?

**Comment by 7kasper** [comment]
@Shevchik There are no errors, but if you open the current implementation, you can see the heads of pc players jump around 128 degrees (to -128 degrees) on pocket edition clients.

**Comment by Shevchik** [comment]
I was sure that mojang only used 256 degree computation for entity teleport, not player. I guess they screwed it up.

**Pull request merged**
