### PR TITLE
[PSPE] Skins

### PR DESCRIPTION
**Pull request by KernelFreeze**
Hello, I'm working with the help of "Mineskins" the support of "Bedrock -> Desktop" skins. For now it loads the player skin data, converts it to .png and uploads the data to Mineskins. I want to keep this pull request open until I implement the packet translation. Thank you for being awesome, people!

### CODE REVIEW

**Comment by KernelFreeze** [comment]
Also, I added as dependencies "Java JWT" for safely decode the user data, and of course, Mineskins.

**Comment by Shevchik** [comment]
That doesn't belong to pspe itself.
See https://github.com/ProtocolSupport/ProtocolSupportPocketStuff

**Comment by 7kasper** [comment]
Awesome!.. but we've already made it... :S

**Comment by MrPowerGamerBR** [comment]
Implemented in ProtocolSupportPocketStuff by yours truly...

...we should remove that from the PSPE project list.

**Pull request closed without merging**
