### PR TITLE
Switch to gradle (Related to #134, #230)

### PR DESCRIPTION
**Pull request by games647**
### Changes:
* Moved /src to /src/main/java -- can be changed if you want to. It's just a convention and changed nothing on the classpath
* Moved /src/plugin.yml to /src/main/resources
* Removed ant file
* Added gradle, IntelliJ, Netbeans gitignore

### Checklist(similar to your ant file):
- [x] Compiles with Java 7
- [X] All dependencies spigot and BuildProcessor
- [X] Download/Update Spigot automatically from your server with `gradle updateSpigot`
- [X] License and plugin.yml is added to the jar file
- [X] Keep the group and project name same to the classpath (against the convention btw)
- [X] Use the same project as in the plugin.yml
- [X] Use latest gradle wrapper version

### Notes:
* Gradle is platform independent. Use `gradlew ` for windows or  `gradle` for *nix systems
* Includes gradle wrapper, which automatically downloads the complete build system
* UpdateSpigot downloads the version from your server and overwrites the existing file
* You could also make nested builds like  `gradle updateSpigot jar ` -> updateSpigot and then buildjar

### Download/Update Spigot

*NIX:
`gradle updateSpigot`

Windows:
`gradlew updateSpigot`

### Building Jar

*NIX:
`gradle jar`

Windows:
`gradlew jar`

Tested with Netbeans 8.1, IntelliJ 216.2.2 and Eclipse Neon

If I should change something. Just say it.

### CODE REVIEW

**Comment by games647** [comment]
I hope I could help you.

**Comment by games647** [comment]
Another idea is to synchronize the plugin.yml file with your build.gradle file. So that you only have to change it one time. I'm looking forward to hear from you.

**Comment by sgdc3** [comment]
Pour Maven :( @games647 xD

**Comment by Shevchik** [comment]
Moved /src to /src/main/java.
Moved /src/plugin.yml to /src/main/resources

Revert this and it can be merged.

**Comment by sgdc3** [comment]
>Moved /src to /src/main/java.
Moved /src/plugin.yml to /src/main/resources

What's the issue with the default maven/gradle directory directory structure?

**Comment by Shevchik** [comment]
I just hate it for an unknown reason. Most likely because it adds useless folders along the way.


As for repo - i don't have one, and most likely never will, but you can add properties to it if you wan't (if it doesn't rename the resulting file).

**Comment by sgdc3** [comment]
>Most likely because it adds useless folders along the way.

Not such an issue, it allows to add unit testing in the future

**Comment by games647** [comment]
>Moved /src to /src/main/java.
Moved /src/plugin.yml to /src/main/resources
What's the issue with the default maven/gradle directory directory structure?

I wonder too, because the IDEs automatically detects this nested folder structure and you see directly the main package.

I forgot to mention that you can then find the final jar in build/libs/

**Comment by Shevchik** [comment]
Move resulting jar to target directory.

Now i just need to configure my build server.

**Comment by games647** [comment]
>Move resulting jar to target directory.

So I should move the jar to /target/ProtocolSupport?

**Comment by Shevchik** [comment]
Yep

**Comment by games647** [comment]
Without a version suffix?

**Comment by Shevchik** [comment]
Yep

**Pull request merged**
