### PR TITLE
ProtocolSupport Pocket Edition

### LINKED ISSUE #304: PE Version?
When you update pe protocol support?

### PR DESCRIPTION
**Pull request by 7kasper**
ProtocolSupport~~Broken~~PocketEdition
--------------
ProtocolSupport - Connecting People

--------------
Fixes #304. Warning: this pr will probably stay open for long 😄 

**What is PSPE?**
ProtocolSupport Pocket Edition is a version of ProtocolSupport that not only allows players from old java editions on your server, but allows Bedrock or Pocket Edition players to play in unison too!

**So why this PR?** 
The thought is that this would be an interesting place to keep a birds-eye overview of what large things still need to be done to make PSPE production ready. **_This will not happen soon, but soon:tm:_**
This is a very very very very very very very large pull request, but it is still fun to see and to keep track of all the code-updates related to this project!
Once PSPE is production ready, it will become standard issue and be merged into the main branch!

**Great! So what needs to be done?**
PSPE is a large project going on for about three years now. Coding has been on and off because of us having busy lives. A lot has been done, _but there's also a lot left to do._  

Here's a list of some (bigger) but important things we still need to do in order to get closer to merge:

- [ ] Improving RakNet implementation and connection stability.
- [ ] Fixing big gameplay affecting bugs.
- [ ] Fixing inventory remapping.
- [ ] Lots of testing, semi-production and otherwise.
- [ ] Performance improvements in all possible areas.
- [ ] Tidying of 'faux' inventory system & slot remapping for PE.
- [ ] Implement some still missing features (mostly 1.13 stuff).
- [ ] Fixing smaller bugs.
- [ ] Remove bloat from PSPS, rework skin api.
- [ ] Fix PSPS to be less hack and more reliable / updatable.

**How do I contribute?** 
We don't mind more devs, more hands make work easier! Perhaps its helping with remaps, perhaps you can help with missing features, packets or improve code. Like previously said, the project is quite large and you might get lost in all the packages and files at first. We also have some standards for style and performance and thread safety. If you think you have what it takes, stroll around the wiki and give us a chat on our discord! (https://discord.gg/QCCDEnn)

**How can I test?**
This project is not finished and we don't recommend using it on any kind of production server. If you really want to help us test, you need to compile the mcpenew branch yourself. Come over to our discord channel and look in the pinned messages of the #mcpe channel to see how (https://discord.gg/QCCDEnn). Do note we already know most missing things, but if they are not reported yet, or you found a bug, please report that on https://github.com/ProtocolSupport/ProtocolSupportPocketIssues/issues

Suggestions are also always welcome!

### CODE REVIEW

**Comment by Lmmb74** [comment]
Shouldn't the goals list get an update? It's been almost 5 months since the last one.

**Comment by EOT3000** [comment]
Suggestion: Use the Nukkit protocol library, instead of decompiling the client: https://github.com/NukkitX/Protocol

**Comment by Shevchik** [comment]
You havent even checked how ps works.

**Comment by sachk** [comment]
You can see at the top of the page that 38k lines of code have been added. Surely, at some point while writing all that one of the multiple people working on this would've realized that using the nukkit protocol library would be a good idea.

**Comment by WesleyVanNeck** [comment]
@sachk I dont think its a good idea protocolsupport tranlates mc Java pakkets that means that we cant use the packets strait of nukkit and of still needs to be compatible with older versions of mc java

**Comment by sachk** [comment]
Sorry, I might've phrased that wrong. I meant that if Nukkit was a good idea, someone working on it would've implemented it already, but no one has yet.

**Comment by EOT3000** [comment]
I meant for pocket edition support

**Comment by EOT3000** [comment]
"Suggestion: Use the Nukkit protocol library, instead of decompiling the pocket edition client" would be what I meant to say

**Comment by Shevchik** [comment]
Doesn't change what i said.

**Comment by EOT3000** [comment]
I know what ps does. it allows other versions of Minecraft to play on the pc server

**Comment by EOT3000** [comment]
pspe allows pe players to play

**Comment by Shevchik** [comment]
Now all you need is to read the code to find out exactly how it is done, and you will understand why this library won't work for us.

**Comment by EOT3000** [comment]
I can't see why. I've read the code plenty of times before. To update to new versions, you need to decompile the client, try to make out what anything means, then add the packets to PSPE. The library will save you the effort. The only problems I can think of that you would have to rewrite everything, and maybe the license.

**Comment by Shevchik** [comment]
Which in the end doesn't save us time, since we will either have to wait for library, read it, understand what is going on with it, then check for possible errors. Or just dig out the information ourselves.

**Comment by EOT3000** [comment]
I guess

**Comment by pppwaw** [comment]
If the idea of nukkit is as good as you say, why does DragonetProxy have to spend a year rewriting it now, and it hasn't been completed yet?

**Comment by EOT3000** [comment]
Because of the chunk data. We don't have a way to convert the java blocks to bedrock ones

**Comment by WesleyVanNeck** [comment]
Well thats already done

**Comment by CZHO404** [comment]
so why has this not been added to the repo yet?

**Comment by OnlyBMan** [comment]
@CZHO404 Mainly because PE support is still very very buggy in it's current state and many things have to be added, fixed, or completely rewritten.

**Comment by CZHO404** [comment]
ok thanks for the reply.

**Comment by pppwaw** [comment]
> 
> 
> Because of the chunk data. We don't have a way to convert the java blocks to bedrock ones

Can we convect the chunk in the proxy?I think it's possible.

**Pull request closed without merging**
