### PR TITLE
Update concrete remapping

### PR DESCRIPTION
**Pull request by jordinjm**
Map concrete to stained clay.

### CODE REVIEW

**Comment by half-cambodian-hacker-man** [comment]
+1 - Excessive use of concrete on a map when ProtocolSupport is used can make the world look like utter ~~shit~~ garbage for players on versions older than 1.12.

**Comment by AppleDash** [comment]
+1

**Comment by Shevchik** [comment]
Concrete hand break time - 9units, stained clay - 6.25. Which means most of the time player won't be actually break a block.

**Comment by MrPowerGamerBR** [comment]
Also, if you don't care about hand break time (and your players raging because they can't break concrete) then use ProtocolSupport's API to remap concrete to stained clay.

**Comment by jordinjm** [comment]
Oh I didn't realize they had different breaking times. I will just make a plugin for it.

**Comment by 7kasper** [comment]
@jordinjm Your best bet is to make a plugin that uses the remapcontroller and gives slowness to legacy players that are trying to break concrete. That way you can seemingly affect the hardness. It just has to be a higher breaktime than concrete and the server will do the rest. If you match the time up correctly, it won't be a nuisance for the player.

**Pull request closed without merging**
