### PR TITLE
Send PC skins to PE players

### PR DESCRIPTION
**Pull request by DaMatrix**
Feel free to close this if you want, just thought somebody might find this useful.

### CODE REVIEW

**Comment by jojoe77777** [comment]
And if the PC player's skin is in slim (Alex) format?

**Comment by DaMatrix** [comment]
good point, didn't think of that :P
it would just show some extra rows of black pixels on the arms

**Comment by Shevchik** [comment]
You can't do it like that, it will block an netty io thread.

**Comment by 7kasper** [comment]
It's funny. I was working on the same thing. Here is my version:
`	public static final byte[] getSkin (String username){
		URL imageLocation;
		try {
			imageLocation = new URL("http://s3.amazonaws.com/MinecraftSkins/" + username + ".png");
		} catch (MalformedURLException e1) {
			return STEVE;
		}
		return new Callable<byte[]>() {
			@Override
			public byte[] call() {
				try {
					return toNetworkData(ImageIO.read(imageLocation));
				} catch (Exception e) {
					return STEVE;
				}
			}
		}.call();
	}`

Of course you'll also need to change the validator to accept old format skins:
`Validate.isTrue(skin.getHeight() == 64 || skin.getHeight() == 32 , "Must be 32 or 64 pixels high");`
Pocket still handles the 64*32 images fine.

**Comment by DaMatrix** [comment]
Same thing though, it still downloads the image on the netty thread, locking it.

**Comment by 7kasper** [comment]
@DaMatrix I wasn't saying it was anything different :)

**Comment by DaMatrix** [comment]
The other thing i can think of would be reading from the SkinsRestorer cache files, assuming that the plugin is present. (not a good fix though :/ )

**Comment by 7kasper** [comment]
So we'll need to stall the particular packet untill the skin is downloaded on another thread and then callback on it someway.

**Pull request closed without merging**
