### PR TITLE
Fixed rabbit size in PSPE

### PR DESCRIPTION
**Pull request by KernelFreeze**
Hello! I added a new metadata remap to send to clients the right size of rabbits. If another change is needed, or something can be done in a better way, don't hesitate to tell me.

### CODE REVIEW

**Comment by magicus** [comment]
It seems complex to just fix the rabbit baby size... I imagine that it is not really just rabbit babies that are off, but all babies, only that it is more visible with rabbits. So I think the solution should be more general. I've always imagined that we'd need to encode the baby size in entitydata.json.

**Comment by WesleyVanNeck** [comment]
@magicus its all rabbits not only babies mostly adults There like from 1.8 size there like mc java small

**Comment by WesleyVanNeck** [comment]
image

@magicus

**Comment by magicus** [comment]
Hm. It still seems overly messy for just rabbits. 

Any idea why this should be needed for just rabbits, but no other mobs? 

Where does the 0.3 and 0.55 factors come from? 

Why the null check for the bounding box? Either we have a bounding box for rabbits (we should!) or we don't, in case something is messed up with entitydata.json, and we should not just ignore it.

I really appreciate that you try to fix this, I'm just not really comfortable with the fix.

**Comment by KernelFreeze** [comment]
Other baby mobs are already working by default, only rabbits need this fix for some reason. I took the sizes from the wiki, maybe it would be better to get them from a constant or even from entitydata.json, you tell me what you prefer, and I can change it.

Also, I don't think the null check is necessary, but I saw that you used it for Giants, I took it from there.

**Comment by magicus** [comment]
Ok, we'll just have to accept that rabbits are different. In that case, I think the fix is good enough. It still has a bit of a "patchy" feel to it, but then again, so has a lot of the PE code :-).

**Comment by Shevchik** [comment]
Missing bounding box should not be ignored, and it should fail in that case.
Giant should have null check removed too if it exists.

**Comment by KernelFreeze** [comment]
Like this?

**Pull request merged**
