### PR TITLE
Fix control vehicle for 1.5.2

### PR DESCRIPTION
**Pull request by BeYkeRYkt**
Fixed:
- [1.5.2] Can't control vehicle - won't be fixed, probably impossible to do this properly

Issues:
- Wrong yaw value of boat.

### CODE REVIEW

**Comment by Shevchik** [comment]
All inbound packets are processed on a network thred, so modifying a properties of an entity is not a good idea.

**Comment by BeYkeRYkt** [comment]
Any idea ?

**Comment by Shevchik** [comment]
Probably receive a custom SteerVehicle packet with overridden handle method. Also stop using spaces, use tabs.

**Comment by BeYkeRYkt** [comment]
Maybe use Bukkit Vector ?

**Comment by BeYkeRYkt** [comment]
I tried to write a custom Steer Vehicle and received such errors:
```
[15:06:20] [Netty Server IO #1/WARN]: io.netty.handler.codec.DecoderException: net.minecraft.server.v1_8_R3.CancelledPacketHandleException
[15:06:20] [Netty Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:280)
[15:06:20] [Netty Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149)
[15:06:20] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[15:06:20] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[15:06:20] [Netty Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[15:06:20] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[15:06:20] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[15:06:20] [Netty Server IO #1/WARN]: 	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
[15:06:20] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[15:06:20] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[15:06:20] [Netty Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
[15:06:20] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
[15:06:20] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
[15:06:20] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
[15:06:20] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
[15:06:20] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
[15:06:20] [Netty Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[15:06:20] [Netty Server IO #1/WARN]: 	at java.lang.Thread.run(Unknown Source)
[15:06:20] [Netty Server IO #1/WARN]: Caused by: net.minecraft.server.v1_8_R3.CancelledPacketHandleException
```
Can I do something wrong?

**Pull request closed without merging**
