### PR TITLE
Make the "command shortcut menu" appear.

### PR DESCRIPTION
**Pull request by magicus**
This is the menu in the chat UI with shortcuts for setting time, weather, and teleporting.

### CODE REVIEW

**Comment by magicus** [comment]
@Shevchik Any progress on this?

**Comment by Shevchik** [comment]
You need to fix comments first

**Comment by magicus** [comment]
Sorry, what comments?

**Comment by Shevchik** [comment]
See spaces should be tabs review

**Comment by magicus** [comment]
This is weird. Did you add a review comment? I can't see it. :-(

Anyway, I see that there were leading spaces instead of tabs, fixed that.

**Pull request merged**
