### PR TITLE
MCPE update!

### PR DESCRIPTION
**Pull request by DaMatrix**
**THIS IS NOT READY FOR MERGE, IT'S JUST A PLACE FOR FEEDBACK ATM**
Essentially just a continuation of the mcpe branch.

### CODE REVIEW

**Comment by MrPowerGamerBR** [comment]
I doubt Shevchik will reuse the old code from the mcpe branch, he will probably delete the old branch and create a new one.

**Comment by DaMatrix** [comment]
I know, this would need somewhat of a rewrite anyway to be able to support multiple MCPE versions.

**Comment by Shevchik** [comment]
Yeah, this branch will be removed, and only a small portion of code will be reused.

**Comment by DaMatrix** [comment]
Oh OK, I'll delete this then and wait until you get started.

**Pull request closed without merging**
