### PR TITLE
Update 1.5.2 health display

### PR DESCRIPTION
**Pull request by EntryPointKR**

### CODE REVIEW

**Comment by Shevchik** [comment]
needsPlayer() should be used only when really needed because the access is async. Are you sure that max health is not sent anywhere so we can cache it?

**Comment by EntryPointKR** [comment]
What's means "cache it"?
This is my best in my understanding for ProtocolSupport.
If the wrong this code, please point out.

**Comment by Shevchik** [comment]
ProtocolSupport has a thing called LocalStorage. It caches data that may be needed by another packet later. See entity spawn and entity metadata transformers.

**Comment by EntryPointKR** [comment]
Like this?

**Comment by Shevchik** [comment]
No, i will commit the proper fix later.

**Pull request closed without merging**
