### PR TITLE
Fix some things FindBugs complain about.

### PR DESCRIPTION
**Pull request by magicus**
To prepare for running FindBugs on the mcpeinventory branch, I started by running FindBugs on mcpenew. I fixed some trivial things, to at least get the FindBugs issue count down a bit.

### CODE REVIEW

**Comment by Shevchik** [comment]
The implements clonable needs to be reverted. We don't follow the clonable contract (since we don't really call Object#clone).

**Comment by magicus** [comment]
@Shevchik Fair enough, I'll revert that. But perhaps the methods should be renamed, so,they don't look like they are following the Java clone contract? E.g makeCopy()?

**Comment by magicus** [comment]
It just hit me that maybe some (or all?j of this issues exist in master as well. Do you want me to retarget the PR, if possible?

**Comment by 7kasper** [comment]
@magicus yes, please pr this to master

**Comment by 7kasper** [comment]
ok that didn'work lol

**Pull request closed without merging**
