### PR TITLE
Use PlayerCommandPreprocessEvent to block reloads

### PR DESCRIPTION
**Pull request by Zbob750**
Switches away from removing the command from the server command map, to using Bukkit's API to block usage. This method is less likely to break should someone make changes to the command map.

Fixes GH-297 in the process.

### CODE REVIEW

**Comment by Shevchik** [comment]
Wtf is that block code, you don't need to iterate to over list here, use a hashset.
Also this won't work if more spaces are added between /reload and arguments, bukkit will parse it fine, but preprocess event receives original message.

**Comment by Zbob750** [comment]
Was trying to keep it simple. Will switch it to a hashset and look into spaces issue.

**Comment by Zbob750** [comment]
Updated, spaces are a non-issue. Feel free to check.

**Comment by Zbob750** [comment]
Easiest way to maintain case insensitivity is with a TreeSet, to do it with a HashSet is going to result in a lot of overengineering just to save an extremely tiny amount of time.

**Comment by Shevchik** [comment]
Or you can just toLowerCase() on message before checking if it exists in the map.

**Comment by Zbob750** [comment]
I really need to pull my head out of my ass tonight. Thanks for pointing that out >.> I didn't even think of it.

**Comment by Shevchik** [comment]
Now just fix the formatting, this project uses tabs, not spaces.

**Comment by Zbob750** [comment]
Woops, fixed

**Pull request merged**
