### PR TITLE
Schism of SpecificRemapper and WatchedType

### PR DESCRIPTION
**Pull request by 7kasper**
Already makes things less awkward.

For now the SpecificRemapper just transforms from WatchedType crudely and the metadata remapper still uses the SpecificRemapper, but that remapper has to be changed anyway.

I just copied most of the values of the SpecificRemapper, and added a few bukkit types.

### CODE REVIEW

**Comment by Shevchik** [comment]
Some formatting notes:
Add spaces between if and (
Add spaces between } (
Use tabs

**Comment by 7kasper** [comment]
@Shevchik Better? Some of the comments don't seem to show nicely in github but they look beautiful in eclipse :stuck_out_tongue:

**Comment by Shevchik** [comment]
Just remove those comments, they are useless anyway (class outline shows everything anyway)

**Comment by 7kasper** [comment]
@Shevchik Developers always seem to have fueds over formatting. I like the comments especially in big classes. Whatever.

**Comment by gdude2002** [comment]
@7kasper Those were pretty useless comments, I agree with @Shevchik - comments should explain _why_ you're doing what you're doing,  not _what_ you're doing. If you're wondering what the code is doing, well.. read the code.

**Comment by 7kasper** [comment]
@gdude2002 It's personal preference. If I come back to old projects I find it very useful if I can quickly see what a class does and where it does that. But I don't mind adapting of course :relaxed:

**Comment by Shevchik** [comment]
Also you can't use the EntityType to get object network ids, they are different.

**Comment by 7kasper** [comment]
@Shevchik What? Are the bukkit ids different from the protocol? Why?
If that is the case I'll put the differing ids back, but I will get something to eat first.

**Comment by Shevchik** [comment]
Because the bukkit ids are the nbt save ids. And network object ids are different from that.

**Pull request merged**
