### PR TITLE
chmod +x ./gradlew

### PR DESCRIPTION
**Pull request by Maxqia**

### CODE REVIEW

**Comment by Shevchik** [comment]
Use tabs for indentation.

**Comment by Maxqia** [comment]
Well eclipse is giving me an error for it, https://docs.oracle.com/javase/7/docs/api/java/util/Iterator.html

**Comment by games647** [comment]
@Maxqia Do you have the JDK 7 or JDK 8 installed? I assume it's, because you still have JDK 7 installed. Java 8 has declared Iterator.remove() as default method.

**Comment by Maxqia** [comment]
I have JDK 8, but it's set to 1.7 compatibility mode by the current build.gradle
https://github.com/ProtocolSupport/ProtocolSupport/blob/716e52a923705f42e9788ac92a9b33e2c396299d/build.gradle#L9

**Comment by games647** [comment]
@Maxqia Often this tries to find JDK 7 and if it doesn't find it, it changes only the bytecode version. New libraries could still be used although they don't exist in Java 7

**Comment by Shevchik** [comment]
The remove method is default in java8, and i'm using java8 to build it. I'm going to drop java7 support soon, so it doesn't ammter anyway.

**Comment by Maxqia** [comment]
Can you bump the java version now then?

**Pull request closed without merging**
